### ISSUE TITLE
ocamlformat uses one column about static int array

### ISSUE THREAD

**Issue by dinosaure** [mirage/decompress#106]
/cc @gpetiot, I'm not sure about which option I should set to have a compact array declaration instead of:
https://github.com/mirage/decompress/blob/f5cdd9a12cbe4d29a8af4ce6034b32862ee53c42/lib/de.ml#L222-L480

**Comment by gpetiot** [comment]
Hi, you can use `break-collection-expressions = wrap`

**Comment by dinosaure** [comment]
Fixed by #107, thanks :+1:.
