### ISSUE TITLE
Incorporating inflator.ml directly into decompress as high-level interface? 

### ISSUE THREAD

**Issue by wiredsister** [mirage/decompress#14]
CC: @yomimono, @Engil, @verbosemode

Any plans for this? I just updated the inflator.ml to mirror Canopy's to make this work for the Syslog project: https://github.com/verbosemode/syslogd-mirage/pull/9

Wondering if there is a better way we can do this other than copying files?

**Comment by Engil** [comment]
I think this was supposed to be incorporated inside ocaml-git (which is the library using it.)
I am maybe wrong but ping @samoht @dinosaure :)

**Comment by wiredsister** [comment]
@yomimono just pointed this out to me: https://github.com/mirage/ocaml-git/pull/145...

**Comment by dinosaure** [comment]
Hmmmhmm, `inflater.ml` is very specific for Irmin project and it has a dependency with `cstruct` and `mstruct`. So, the goal is to integrate `Decompress` in `ocaml-git` (I don't want any dependencies in `Decompress`) but @samoth and me work on the performance (specifically with `Inflate`) and when we have a good result, we will provide a Interface inside `ocaml-git`.

**Comment by samoht** [comment]
note: I'm fine to add decompress as a depopt in ocaml-git whenever you want. I just have some reservation about it being pulled in by default :-)

**Comment by samoht** [comment]
Actually, given that it doesn't bring any dependency, I am fine to have it in ocaml-git by default, but not just as the main implementation for now on (e.g. the user should be able to use the module it if wants it). Not sure how easy it is to do but patches are welcome.

**Comment by dinosaure** [comment]
Done from a long time ago.
