### ISSUE TITLE
gzip

### ISSUE THREAD

**Issue by dinosaure** [mirage/decompress#27]
It's only about the header, so (I think), it's easy to implement this (@juanchanco did already this feature but in the old version of Decompress).

This issue is not for the next version of Decompress (1.0).

**Comment by hcarty** [comment]
Would this make more sense in some future [ezdecompress](https://github.com/oklm-wsh/Decompress/issues/25#issuecomment-283774586) library?

**Comment by dinosaure** [comment]
Hmmhmm, I'm open to any suggestion and I need to look deeply what is `gzip` but, with my aknowledge, I can say than: decompress is very close to the `zlib` format (we check a `zlib` header, the checksum is `adler32`) and these points are incompatible with the `gzip` format (the header is more precise and the checksum is different).

So, in my head, I need to change some parts of decompress to handle the `gzip` format. A good news is that `zlib` and `gzip` respect both the [RFC1951](https://tools.ietf.org/html/rfc1951) - and it's why I think it's a minor change.

I follow the `zlib` implementation which handles `zlib` and `gzip` format. So, I can't say more for this moment but, it can be a good idea if I don't need to change decompress 👍 !

**Comment by hcarty** [comment]
I have https://github.com/hcarty/ezgzip which could benefit from a decompress backend once/if I get time to learn to use decompress!  Please feel free to take anything from it if you'd like to add gzip support to decompress directly.

ezgzip attempts to minimally http://www.gzip.org/zlib/rfc-gzip.html#specification in a minimally conformant way by parsing (and ignoring) optional headers.  It's missing thorough testing at this point.  It exists mainly to allow easy gzip (de)compression in memory.

**Comment by XVilka** [comment]
Would be nice to have this too as a part of decompress library.

**Comment by dinosaure** [comment]
I definitely need to come back to `decompress`, again I plan to focus on next week.

**Comment by dinosaure** [comment]
Close by #60
