### ISSUE TITLE
Export RFC1951 interface

### ISSUE THREAD

**Issue by dinosaure** [mirage/decompress#39]
`zlib` wraps only the RFC1951 standard - so we already implemented it. It could be interesting to export only the RFC1951 decoder/encoder (in a smart way ...) and avoid the `zlib` header and the Adler-32 checksum at the end.

**Comment by dinosaure** [comment]
Done by #41 & #42.

**Comment by cfcs** [comment]
@dinosaure it would be very nice to have a release with this! <3

**Comment by cfcs** [comment]
Cool! It's not super urgent, would just be nice to have at some point. :)
