### ISSUE TITLE
Infinite loop and eats all memory

### ISSUE THREAD

**Issue by XVilka** [mirage/decompress#49]
I have this code
```ocaml
(* Data is a Bigarray.Array1 of chars *)
(* FIXME: For some reason it eats memory like crazy on one sample *)
let unzlib_raw ba =
    let open Decompress in
    Printf.printf "ZLib: Before unpack\n";
    let data = Util.ba_to_bytes ba in
    let datalen = Bytes.length data in
    Printf.printf "ZLib: datalen = 0x%x\n" datalen;
    Out_channel.flush Out_channel.stdout;
    let inputbuf = Bytes.create 0xFFFF in
    let outputbuf = Bytes.create 0xFFFF in
    let window = Window.create ~proof:B.proof_bytes in
    let pos = ref 0 in
    let res = Buffer.create datalen in
    Zlib_inflate.bytes inputbuf outputbuf
    (fun inputbuf ->
        let n = min 0xFFFF (datalen - !pos) in
        (* TODO: More efficient algorithm without copy *)
        Bytes.blit data !pos inputbuf 0 n;
        pos := !pos + n;
        n)
    (fun outputbuf len ->
        Printf.printf "ZLib: outfun len = 0x%x\n" len;
        Out_channel.flush Out_channel.stdout;
        Buffer.add_subbytes res outputbuf 0 len;
        0xFFFF)
    (Zlib_inflate.default window)
    |> function
        | Ok _ ->
                Printf.printf "ZLib: Unpack successful\n";
                Some (Buffer.contents res)
        | Error e ->
                Printf.printf "ZLib: Unpack failure\n";
                None
```
And I have a chunk of the data (it might be not a valid Zlib data, but it should still return a failure then, instead of perpetuating and eating all of memory until it gets OOM-killed. Attaching a ZIP archive of it (note it is not the ZIP causing problems, it is `faulty_data.bin` file inside)
[faulty_data.zip](https://github.com/mirage/decompress/files/2313502/faulty_data.zip)

**Comment by dinosaure** [comment]
Ok I will see next week this bug. Thanks for report.

**Comment by dinosaure** [comment]
Hmmhmm, firstly, two points:
* `faulty_data.bin` is huge and I need to notice you than `unzlib_raw` will grow `res` to something upper than 7,3M. In other words, at the end, you should have a big buffer on your RAM. It's not the purpose of your issue but the `decompress` API was thought to avoid this kind of memory issue (specially for `ocaml-git`) - and provide, btw, a stream API memory bounded.

* `faulty_data.bin` is an invalid `zlib` content: `./zpipe -d < faulty_data.bin > /dev/null` returns `invalid or incomplete deflate data`.

This is some notes about what I can say currently, but, yes, `decompress` has bug obviously on your input - and should just leave up like what `zlib` does.

**Comment by XVilka** [comment]
It is obviously invalid, but decompress shouldn't react like this. My workflow is - check if the data chunk has magic bytes, maybe some headers set, then feed to `decompress`. If it will return error - skip and go for the next chunk.

**Comment by dinosaure** [comment]
I found the bug, I missed a check about extraction of Huffman tree from inflate flow and, now `decompress` fails correctly on your input (like what `zlib` does). About memory consumption, it's much more about your code which grows automatically a buffer - so it's outside the scope of `decompress`, you can have the infinite loop without memory leak with the `dpipe` binary (eg. `./dpipe.exe --mode=inflate < faulty_data.bin > /dev/null`) for example.

A PR will appear soon. Thanks for reporting.
