### ISSUE TITLE
Allow to specify wbits value in Inflate too

### ISSUE THREAD

**Issue by XVilka** [mirage/decompress#50]
Like it is possible with "Zlib_deflate.default", like Python zlib allows it: https://docs.python.org/3/library/zlib.html

**Comment by dinosaure** [comment]
Currently (trunk), it's possible to [specify `wbits`](https://github.com/mirage/decompress/blob/master/lib/decompress.mli#L260) like Python `zlib` (it's an optional argument) when you want a compression. You can not specify it when you want a decompression because it was specified by the flow (see `zlib`'s header).

**Comment by dinosaure** [comment]
Ok, I understand and in this case, it's more about `rfc1951` (which does not parse `zlib`'s header) than `decompress` (which expect a `zlib` header). Purpose of this task is more about a thin control of the memory consumption or an expected input with strong constraints (the limited expected distances available in the input flow) than anything else.

Indeed, if you want to limit the window size (and, btw, allocate less than 32k) when you decompress/inflate, you should have an error if the input flow has distance bigger than the window size. I can implement it but `rfc1951` will be less resilient (as a _best-effort_ inflator).

So if it's exactly what you want, I will happy to implement it 👍 .

**Comment by XVilka** [comment]
Yes, I had particular data which was using the `-11` window bits value. So implementing this on RFC1951 level is fine.

**Comment by dinosaure** [comment]
See #55

**Comment by dinosaure** [comment]
I need to add some tests and I will make a new release of it.

**Comment by dinosaure** [comment]
Distance (and more generally `window`) was already checked with #55 but #56 adds some tests about that (from `zlib`). Currently, it's not perfect and I need to figure out about some specials cases when `decompress` fails and `zlib` inflates - indeed, some tests from `zlib` expect `zlib`'s behavior (about input/output buffer).

Then, we have some others projects which wait a new release of `decompress` now.

By this way, next release will be `0.8.1` and not `0.9`.
