### ISSUE TITLE
Find the data end without actual unpacking

### ISSUE THREAD

**Issue by XVilka** [mirage/decompress#76]
Formats like GZip do not define the end marker of the stream, and doing actual decompression for just finding out the size is overkill. Is it possible to do a "lighter" version of the walking algorithm to find the end of compressed data? And export this as an API.

**Comment by dinosaure** [comment]
> Formats like GZip do not define the end marker of the stream, and doing actual decompression for just finding out the size is overkill.

Yes, it's because end of stream can be reached only if we know that we process the last block and if we get the `EOB` _op-code_. So we must compute at least:
- each block headers to know if it's the last block or not
    + if the block is `FLAT`, we know the length of it and can go to the next block or reach end-of-stream
    + if the block is `FIXED`, we need to _mask_ any 2 bytes of the stream with the series of bits which corresponds to `EOB` to know where is the end-of-block.
    + if the block is `DYNAMIC`, we need to unpack the huffman-tree to know the series of bits corresponding to `EOB` and apply the mask on it as `FIXED`.

Finally, a light computation seems not possible from what I know ...

**Comment by XVilka** [comment]
Yes, seems it would require to run at least half of the decompression algorithm. Too much work for little benefit. I wonder what algorithm designers thought!?

**Comment by copy** [comment]
@XVilka Maybe to support concatenation of archives, e.g.:

```
% echo foo > foo; gzip foo; echo bar > bar; gzip bar
% cat foo.gz bar.gz | zcat
foo
bar
```

Also, streaming compression does not know the size beforehand.

**Comment by XVilka** [comment]
Ok, I am closing this then. Thanks for the answers!
