### ISSUE TITLE
Index out of bounds in de.ml

### ISSUE THREAD

**Issue by b1gtang** [mirage/decompress#83]
Attaching is an archive of the input data buffer, that might be not a valid zlib data, but raise an exception.

```
Uncaught exception:

  (Invalid_argument "index out of bounds")

Raised by primitive operation at file "lib/de.ml", line 1010, characters 20-38
Called from file "lib/de.ml", line 1319, characters 27-37
Called from file "lib/gz.ml", line 450, characters 12-31
Called from file "lib/gz.ml" (inlined), line 553, characters 17-22
```

[test.bin.zip](https://github.com/mirage/decompress/files/4550155/test.bin.zip)

**Comment by dinosaure** [comment]
According `file`, the given document is a `gzip` flow. Currently, it's an invalid file where `gzip.1.6` fails on it at the same position than `decompress` - so it's a good news. But of course `decompress` should not returns an `Index ouf of bounds` but a proper error.

**Comment by dinosaure** [comment]
#88 should properly fix your problem, let me try to simplify your example.
