### ISSUE TITLE
Library "decompress" not found with dune.2.5.1 and Multicore OCaml 4.10.0

### ISSUE THREAD

**Issue by shakthimaan** [mirage/decompress#86]
I am trying to build decompress.1.1.0 using dune.2.5.1 for Multicore OCaml 4.10.0. It builds and installs fine, but, when I try to use it using:
```
(libraries checkseum.ocaml decompress)
```
I get the following error:
```
File "benchmarks/decompress/dune", line 4, characters 29-39:
4 |   (libraries checkseum.ocaml decompress))
                                 ^^^^^^^^^^
Error: Library "decompress" not found.
```
Source: https://github.com/ocaml-bench/sandmark/blob/master/benchmarks/decompress/dune
The above works fine with decompress.0.8.1 with dune-2.5.1 and Multicore OCaml 4.10.0 though! As mentioned in the README for issue https://github.com/mirage/decompress/issues/47, I then tried the following syntax:
```
(libraries (checkseum.ocaml decompress)))
```
But, I get the following error:
```
File "benchmarks/decompress/dune", line 4, characters 13-41:
4 |   (libraries (checkseum.ocaml decompress)))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Atom or quoted string expected
```
How can this be resolved?

**Comment by dinosaure** [comment]
Hi, `decompress.1.0.0` introduces a new package layout where the package `decompress` is a _meta_-empty package which have nothing. Then, 3 packages exists:
- `decompress.de` which implements RFC1951
- `decompress.zl` which implements Zlib
- `decompress.gz` which implements Gzip

So it depends on what you want. I can infer that you probably want Zlib and in this case, a `dune` file should be:
```
(executable
 (name my_exe)
 (libraries checkseum.ocaml decompress.zl))
```

Then, the layout of modules changes a bit too where the module `Decompress` does not exist anymore but `Zl` (if you link with `decompress.zl`) exists. I just discovered that the documentation was not updated properly but now you can get it now at this address: https://mirage.github.io/decompress/decompress/Zl/index.html

For a normal use (without a micro control of allocation), [`Higher`](https://mirage.github.io/decompress/decompress/Zl/Higher/index.html) is the most easy entry-point.

I should update the `README.md` about this new version. If you have any question, please don't hesitate - I will close this issue when I will update the `README.md`.

**Comment by shakthimaan** [comment]
I have made the following changes:
* Used `decompress.zl` in the dune file.
* Updated to use `open De` instead of `open Decompress`.
Now I get this error:
```
File "benchmarks/decompress/test_decompress.ml", line 6, characters 27-45:
6 | exception Deflate_error of Zlib_deflate.error
                               ^^^^^^^^^^^^^^^^^^
Error: Unbound module Zlib_deflate

```
What am I missing?

**Comment by dinosaure** [comment]
> What am I missing?

The transition is a bit more complex than that, `Zlib_deflate.error` does not exists anymore and all the API was updated since `1.0.0` (I did not detailed how to update an `decompress.0.8.0`'s code to `decompress.1.0.0` but I notified a huge breaking change at the release).

I can take a look and propose a PR to help you about the migration :+1:.
